name: ClearItem
main: com.mcsyr.clearitem.Main
softdepend: [PlaceholderAPI]
version: 3.2.1-SNAPSHOT
author: Luo_ma & KlNon
commands:
   clearitem:
     aliases: [citem, ci]
     usage: /citem open
     description: 打开公共垃圾桶
